### ISSUE TITLE
Port is not being set properly

### ISSUE THREAD

**Issue by Dreadarm** [ohmcodes/WindowsGSM.Palworld#1]
I noticed that you said you left default ports because the devs supposedly said they cant be set, this is untrue, I modified the MOE plugin to run this game and port settings worked just fine. There is also a port setting in the game config file where it can be set. please update and fix. <3<3

**Comment by Dreadarm** [comment]
https://tech.palworldgame.com/dedicated-server-guide

We can manually control ports by adding this line to the params.
port=12345

**Comment by ohmcodes** [comment]
if you set the port on WGSM settings yes you can i just put 8211 as default, thats only for start param doesnt change the ini file and thats for future update that automate the changes from wgsm to ini file

**Comment by ohmcodes** [comment]
I got it sorted i found out the original arguments is port=xxxx then the other guide for community servers says -publicport=xxxx this article can be found here https://tech.palworldgame.com/community-server-guide
