### ISSUE TITLE
how to change server config (ex: ExpRate, DeathPenalty)

### ISSUE THREAD

**Issue by mingi84** [ohmcodes/WindowsGSM.Palworld#11]
I modified the 'servers/1/serverfiles/Pal/Saved/Config/WindowsServer/PalWorldSetting.ini' file  ( Edited by referring to the DefaultPAlWorldSettings.ini file)
 and restarted the server, but the file is initialized  ( empty) and the settings are not applied.

**Comment by ohmcodes** [comment]
> I modified the 'servers/1/serverfiles/Pal/Saved/Config/WindowsServer/PalWorldSetting.ini' file ( Edited by referring to the DefaultPAlWorldSettings.ini file) and restarted the server, but the file is initialized ( empty) and the settings are not applied.

make sure the server is turned off before editing and saving PalworldSettings.ini

**Comment by mingi84** [comment]
Of course, I edited the PalworldSettings.ini file with the server turned off and then turned the server on. Then, the PalworldSettings.ini file will be initialized. (empty file)

**Comment by ohmcodes** [comment]
> Of course, I edited the PalworldSettings.ini file with the server turned off and then turned the server on. Then, the PalworldSettings.ini file will be initialized. (empty file)

this happens to me and found out that its still running, check task manager if no palworld running coz if you turn on/off the server the rewrite function triggered and if its blank in the 1st time you run that instance it will rewrite it as blank
