### ISSUE TITLE
The server turns on, works, but does not change the status to started

### ISSUE THREAD

**Issue by bnubruno** [ohmcodes/WindowsGSM.Palworld#14]
After the last update my server no longer goes to "started" status. But everything continues to work.

I'm using Windows 11 PRO

![image](https://github.com/ohmcodes/WindowsGSM.Palworld/assets/10691038/1ee36367-299d-4b35-96a4-55d4c0c72dcd)

**Comment by ohmcodes** [comment]
> After the last update my server no longer goes to "started" status. But everything continues to work.
> 
> I'm using Windows 11 PRO
> 
> ![image](https://private-user-images.githubusercontent.com/10691038/300317285-1ee36367-299d-4b35-96a4-55d4c0c72dcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1OTc0MTgsIm5iZiI6MTcwNjU5NzExOCwicGF0aCI6Ii8xMDY5MTAzOC8zMDAzMTcyODUtMWVlMzYzNjctMjk5ZC00YjM1LTk2YTQtNTVkNGMwYzcyZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA2NDUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMmIxMTU2MzgyYzJiZTM5MzNiODdiYTI1NWM2NTZkOWJjMWFhNjkyMjVlMDRmNWRlYzM5YzM0Y2M2NjdkZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iyClIrdqj3tk8BREH24B0PsWz0bhuO2v3dmVXw3LbyA)

issue still persist? i tried to update mine no problem
