### ISSUE TITLE
Problems connecting to the Palworld Server

### ISSUE THREAD

**Issue by leonardo180** [ohmcodes/WindowsGSM.Palworld#16]
Good morning, please forgive me for my bad English. :)

I'm trying to host a game server called Palworld on a Windows 10 machine. Currently, I'm facing difficulties in allowing my friends to connect using my public IP address. I have consulted many guides to resolve the problem without success.

Premises:
I have successfully opened ports 8211-8212-27015-27016 on my router in both UDP and TCP.
I have correctly configured my Windows firewall with the ports mentioned above.
I set the server address to the public address provided by my Internet Service Provider (ISP).

Having nothing left to test I opened a DMZ on my router to the server's IP address and disabled the Windows firewall but the problem persists.
I even attempted to change the game's destination port from the default port 8211 to 25565, but to no avail.

I have clearly already attempted to reboot my ISP provider's modem, routers and switches but nothing has worked.

It should be noted that this is not my first experience managing private game servers.
Also, the parameters I start the server with already include "EpicApp=PalServer".

What could be the possible causes of this problem?

**Comment by ohmcodes** [comment]
> Good morning, please forgive me for my bad English. :)
> 
> I'm trying to host a game server called Palworld on a Windows 10 machine. Currently, I'm facing difficulties in allowing my friends to connect using my public IP address. I have consulted many guides to resolve the problem without success.
> 
> Premises: I have successfully opened ports 8211-8212-27015-27016 on my router in both UDP and TCP. I have correctly configured my Windows firewall with the ports mentioned above. I set the server address to the public address provided by my Internet Service Provider (ISP).
> 
> Having nothing left to test I opened a DMZ on my router to the server's IP address and disabled the Windows firewall but the problem persists. I even attempted to change the game's destination port from the default port 8211 to 25565, but to no avail.
> 
> I have clearly already attempted to reboot my ISP provider's modem, routers and switches but nothing has worked.
> 
> It should be noted that this is not my first experience managing private game servers. Also, the parameters I start the server with already include "EpicApp=PalServer".
> 
> What could be the possible causes of this problem?

Edit config (button) on WGSM change Server IP to IP address of your server local machine (eg: 192.168.x.x)
Set Game Port = 8211 and QueryPort = 8212
port forward 8211 and 8212 both TCP/UDP
add firewall rules in your Inbound both TCP/UDP 8211,8212
if not working maybe your ISP block port forwarding try use zerotier
download the latest version of the plugin

**Comment by leonardo180** [comment]
> > Buongiorno, per favore perdonatemi per il mio pessimo inglese. :)
> > Sto cercando di ospitare un server di gioco chiamato Palworld su un computer Windows 10. Attualmente ho difficoltà a consentire ai miei amici di connettersi utilizzando il mio indirizzo IP pubblico. Ho consultato molte guide per risolvere il problema senza successo.
> > Premesse: ho aperto con successo le porte 8211-8212-27015-27016 sul mio router sia in UDP che in TCP. Ho configurato correttamente il mio firewall Windows con le porte sopra menzionate. Ho impostato l'indirizzo del server sull'indirizzo pubblico fornito dal mio provider di servizi Internet (ISP).
> > Non avendo più nulla da testare, ho aperto una DMZ sul mio router sull'indirizzo IP del server e ho disabilitato il firewall di Windows, ma il problema persiste. Ho anche tentato di cambiare la porta di destinazione del gioco dalla porta predefinita 8211 a 25565, ma senza alcun risultato.
> > Ho chiaramente già tentato di riavviare il modem, i router e gli switch del mio provider ISP ma non ha funzionato.
> > Va notato che questa non è la mia prima esperienza nella gestione di server di gioco privati. Inoltre, i parametri con cui avvio il server includono già "EpicApp=PalServer".
> > Quali potrebbero essere le possibili cause di questo problema?
> 
> Modifica configurazione (pulsante) su WGSM cambia l'IP del server nell'indirizzo IP della macchina locale del server (ad esempio: 192.168.xx) Imposta la porta di gioco = 8211 e QueryPort = 8212 port forward 8211 e 8212 entrambi TCP/UDP aggiungi regole firewall in entrambi in entrata TCP/UDP 8211,8212 se non funziona forse il tuo ISP blocca il port forwarding prova a usare zerotier scarica l'ultima versione del plugin

None of this is working for now.
I have also heard from my ISP provider who confirms that they are not blocking anything.
I also have other services hosted and published such as HomeAssistant, Plex, Arma3 server and in none of these cases have I encountered any problems with my ISP.

These are the rules from the local machine's firewall:


```
New-NetFirewallRule -DisplayName "Allow_TCP_8211_Palworld" -Direction Inbound -Protocol TCP -LocalPort 8211 -Action Allow

New-NetFirewallRule -DisplayName "Allow_UDP_8211_Palworld" -Direction Inbound -Protocol UDP -LocalPort 8211 -Action Allow

New-NetFirewallRule -DisplayName "Allow_TCP_8212_Palworld" -Direction Inbound -Protocol TCP -LocalPort 8212 -Action Allow

New-NetFirewallRule -DisplayName "Allow_UDP_8212_Palworld" -Direction Inbound -Protocol UDP -LocalPort 8212 -Action Allow
```

Similarly to what happens for the other servers, I configured portforwarding for the 8211 and 8212 but nothing.

![image](https://github.com/ohmcodes/WindowsGSM.Palworld/assets/80856701/2dafe15f-d1ac-47a5-8485-42d12fe429f7)

Furthermore, as I wrote before and only in order to verify that there was not a firewalling problem, I did some tests with a DMZ towards the IP address of my router's server and disabled the Windows firewall and it didn't work.

Likewise, I would have liked to exclude VPN and SD-WAN solutions, but if I have no alternatives I will adapt.

Can you think of anything else you can check out?

**Comment by ohmcodes** [comment]
is this the same machine as arma3? i wonder if you could stop arma 3 and replace palworld port to arma3 working 2 ports, if not same idea install palworld on arma3 environment use its port then check if it will work if so then that machine has something

**Comment by leonardo180** [comment]
> is this the same machine as arma3? i wonder if you could stop arma 3 and replace palworld port to arma3 working 2 ports, if not same idea install palworld on arma3 environment use its port then check if it will work if so then that machine has something

I did what you recommended. Indeed more.
I got a new machine, which I was supposed to work on anyway, installed Proxmox, created a new Win10 Pro VM.
Subsequently I reinstalled WindowsGSM, the plugin and went through the old backup. Unfortunately I still get the same error and I don't think I can get out of it.

Without listing them again I followed all the steps already described previously.

**Comment by ohmcodes** [comment]
> > is this the same machine as arma3? i wonder if you could stop arma 3 and replace palworld port to arma3 working 2 ports, if not same idea install palworld on arma3 environment use its port then check if it will work if so then that machine has something
> 
> I did what you recommended. Indeed more. I got a new machine, which I was supposed to work on anyway, installed Proxmox, created a new Win10 Pro VM. Subsequently I reinstalled WindowsGSM, the plugin and went through the old backup. Unfortunately I still get the same error and I don't think I can get out of it.
> 
> Without listing them again I followed all the steps already described previously.

its definitely your VM, coz everyone doesnt have a problem with WGSM and the plugin itself, try it to your gaming pc and check what you've missed
