### ISSUE TITLE
Import Game Server

### ISSUE THREAD

**Issue by tuvok81** [ohmcodes/WindowsGSM.Palworld#17]
hey i have the Problem for this Plugin to import a existent Server

![grafik](https://github.com/ohmcodes/WindowsGSM.Palworld/assets/30367063/bacba07c-d4ff-471e-ba5a-5719d8569253)

can anybody help me for this Problem?

**Comment by ohmcodes** [comment]
> hey i have the Problem for this Plugin to import a existent Server
> 
> ![grafik](https://private-user-images.githubusercontent.com/30367063/308237715-bacba07c-d4ff-471e-ba5a-5719d8569253.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NTUwMTQsIm5iZiI6MTcwOTg1NDcxNCwicGF0aCI6Ii8zMDM2NzA2My8zMDgyMzc3MTUtYmFjYmEwN2MtZDRmZi00NzFlLWJhNWEtNTcxOWQ4NTY5MjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIzMzgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MDE2ZThkYjI4OGJjOTg4YzkzMWViN2RhMmZjMzhiZmUxNWZhZjI3OWNjZTJmNTBhOWE4ZjY1M2U5OWE2YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aqZP06V7i_WRd4_DCtyQxl3jA7mXI9bQFGx4ASRfw74)
> 
> can anybody help me for this Problem?

the import function of WGSM should be the file that you have exported not just any other files
