### ISSUE TITLE
Changes to Palworldsettings.ini does not change anything from server

### ISSUE THREAD

**Issue by wiikid3000** [ohmcodes/WindowsGSM.Palworld#18]
If I change Palworldsettings.ini settings, it does not change the behavior of the game server. The Palworldsettings.ini I am altering is in serverfiles\Pal\Saved\Config\WindowsServer. Is there somewhere else this is overridden? I have to transfer it locally and start single-player and change world settings there, in game, to make changes.

**Comment by ohmcodes** [comment]
> If I change Palworldsettings.ini settings, it does not change the behavior of the game server. The Palworldsettings.ini I am altering is in serverfiles\Pal\Saved\Config\WindowsServer. Is there somewhere else this is overridden? I have to transfer it locally and start single-player and change world settings there, in game, to make changes.


if world settings exists you cant do anything on Palwordsettings.ini
