### ISSUE TITLE
[NOTICE] Server fail to stop gracefully

### ISSUE THREAD

**Issue by SovereignGFC** [ohmcodes/WindowsGSM.Palworld#22]
**Occurs:** After the 0.2.0.6 update on April 3, 2024.
**Expect:** The server to shut down through WindowsGSM without this message.
**Instead:** The server passes through some kind of message to WindowsGSM that it was not closed properly.

**Tried:** Changed the close command from "^c" to "/AdminPassword {Password} /Shutdown {Time} /DoExit" (having found suggestions on reddit regarding closing Palworld dedicated servers).

Same result of the not stopped gracefully message.

**Comment by ohmcodes** [comment]
sending rcon command on cmd command will not work as it is not rcon
