### ISSUE TITLE
Importing server: fail to find PackageInfo.bin

### ISSUE THREAD

**Issue by Argo-theLearner** [ohmcodes/WindowsGSM.Palworld#3]
this does not seem to exist in the server files. Is there something else this needs pointed to or does the import function not work yet?

**Comment by itkujo** [comment]
You manual copy the plugin into the windowsgsm plugin folder.

**Comment by Argo-theLearner** [comment]
> You manual copy the plugin into the windowsgsm plugin folder.
yes, my apologies for not clarifying. I already have the plugin installed. I meant the import function seems to be looking for a file that doesn't exist in the folder. Unless I'm pointing it in the wrong direction.
![image](https://github.com/ohmcodes/WindowsGSM.Palworld/assets/22647036/1bec2362-a190-40de-b7a8-47d1796a67c1)

**Comment by ohmcodes** [comment]
> yes, my apologies for not clarifying. I already have the plugin installed. I meant the import function seems to be looking for a file that doesn't exist in the folder. Unless I'm pointing it in the wrong direction. ![image](https://private-user-images.githubusercontent.com/22647036/298471088-1bec2362-a190-40de-b7a8-47d1796a67c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTgxMjgsIm5iZiI6MTcwNjA5NzgyOCwicGF0aCI6Ii8yMjY0NzAzNi8yOTg0NzEwODgtMWJlYzIzNjItYTE5MC00MGRlLWI3YTgtNDdkMTc5NmE2N2MxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEyMDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiN2RmMzFhOGE3NjI0OWJhYzNhZDMyNmQ1YWFjZDQxOTMzYTczZWRjOTJjNTM1NGVjOGEyN2Q0MTZlYWE0MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UNAqWW1hdUBFr7buSpDb-2qxGtrEdovNvuMAUpx72tU)

this is only working if you backup your server through WGSM, else you have to copy your save and reinstall the server
