### ISSUE TITLE
Param / ini file don't seem to be taking. 

### ISSUE THREAD

**Issue by itkujo** [ohmcodes/WindowsGSM.Palworld#4]
I can't seem to get any Params to take effect. I also tried the .ini file but my Server Admin Password never changes or the server name or anything else. Could you please help. I'm not sure what i am missing.

**Comment by kriegsmarine** [comment]
edit config and add server start param -adminpassword="" 
![AnyDesk_2yXlDSj9Jd](https://github.com/ohmcodes/WindowsGSM.Palworld/assets/13672303/bd03b0c0-4dab-4a72-80f3-66fc7f947e3e)

**Comment by itkujo** [comment]
I'm going to try again today but that's where we put it and it doesn't seem to want to take. I can always give you remote access to our server so that you can see what I'm talking about if you're interested.

**Comment by ohmcodes** [comment]
try the new version it is working on my end
