### ISSUE TITLE
I want to run two Palworld game servers on one server, how should I do it?

### ISSUE THREAD

**Issue by whthte578** [ohmcodes/WindowsGSM.Palworld#6]
I tried modifying the port and query port, and it worked. I was able to successfully connect to the second game service. However, the game saves seem to use the same file, and I'm worried about potential conflicts, so I stopped trying.

Does anyone have similar experiences to share? How can I correctly launch a second game service on the same server?

**Comment by ohmcodes** [comment]
did you install two Palworld server? if so it will not use the same file
